### ISSUE TITLE
Regarding the "isset($this->Log->_schema lines"

### ISSUE THREAD

**Issue by k-risc** [josegonzalez/cakephp-log#4]
Regarding the "isset($this->Log->_schema lines" (that were only removed for save related functions). Isn't it generally a bad approach (or even simply wrong) to try to access protected properties?

As far as I know isset() should always return false when you try to check for a protected property from outside the classes code, no matter whether it contains a value or not.

**Comment by josegonzalez** [comment]
Yes, it is. This code was written 5 years ago though, so you'll have to forgive me if it's not the greatest show of PHP code quality.

**Comment by k-risc** [comment]
No worries, just wanted to check. It's all forgiven, of course. ;)

**Comment by josegonzalez** [comment]
Note: no idea if this even works with the latest cakephp 2.x release. I totally forgot it existed :P

**Comment by k-risc** [comment]
It does. We use it in 2.8.0, although heavily adapted and extended. And it still works.

But after a PHP update on our test server we are having issues coming from using isset with protected properties. But we'll manage. It's all good. ;)

**Comment by josegonzalez** [comment]
Feel free to submit a PR, I'd be happy to get this into a somewhat modern state :P
